typography_spectrum: 0.9618980197701603
color:
  brandStrength: 0.8098178098443896
  lightness: 0.21921075670979917
  saturation: 0.5387826161459088
  rhythmicContrast: 0.12998049124144018
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.17997708986513317
author:
  name: Jorge Grippo
  email: jorge.grippo@gmail.com
  url: 'http://www.grippo.com'
name: Lista de Negocios
title: Una idea simple
description: El poder de publicar es poder publicar
